name: Publish to PyPI

on:
  release:
    types: [published]

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
      # url: https://pypi.org/project/datatrees/
    permissions:
      contents: write
      id-token: write  # Required for OIDC PyPI publishing
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: release
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
    
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Set package version from tag
      run: |
        version="${{ github.event.release.tag_name }}"
        version="${version,,}"  # Convert to lowercase
        version="${version#v}"  # Remove 'v' prefix if present
        echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        verbose: true
        print-hash: true
    
    - name: Sign published artifacts
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: ./dist/*.tar.gz ./dist/*.whl
        release-signing-artifacts: true